StoreFront.UI.MVC/Controllers/FiltersController.cs
using Storefront.DATA.EF;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Data.Entity;//This was added for the .Include() method

//Added after installing NuGet for PagedList.MVC
using PagedList;

namespace StoreFront.UI.MVC.Controllers
{
    public class FiltersController : Controller
    {
        private StoreFrontDB db = new StoreFrontDB();

        public ActionResult ArtistsQS(string searchFilter)
        {
            //If its the firs time viewing the page or the user just hits search without entering anything, return all artists.
            if (String.IsNullOrEmpty(searchFilter))
            {
                var artists = db.Artists;
                return View(artists.ToList());
            }
            else
            {
                //this is written in linq method syntax
                var searchResults = db.Artists.Where(x => x.FirstName.ToLower().Contains(searchFilter.ToLower()) || x.LastName.Contains(searchFilter) ||
                x.Country.Contains(searchFilter) || x.State.Contains(searchFilter) || x.ZipCode.Contains(searchFilter));

                return View(searchResults.ToList());

            }
           
        }

        public ActionResult AlbumsQS(string searchFilter)
        {
            //If its the firs time viewing the page or the user just hits search without entering anything, return all artists.
            if (String.IsNullOrEmpty(searchFilter))
            {
                var albums = db.Albums;
                return View(albums.ToList());
            }
            else
            {
                //this is written in linq method syntax
                var searchResults = db.Albums.Where(x => x.AlbumTitle.ToLower().Contains(searchFilter.ToLower()));

                return View(searchResults.ToList());

            }

        }

        //Server side paging example with PageList.MVC (NuGet) (this does not work the correct way right now)
        public ActionResult AlbumsMVCPaging(string searchString, int page = 1)//default to first page if nothing is passed to the param
        {
            //Variable for how many records to show for page size, this variable can be changed based on how much I want to show.
            int pageSize = 5;


            //for PagedList to function, we MUST sort our collection
            var albums = db.Albums.OrderBy(x => x.AlbumTitle).ToList();

            #region Search

            if (!String.IsNullOrEmpty(searchString))
            {
                albums = albums.Where(x => x.AlbumTitle.Contains(searchString)).ToList();
            }

            ViewBag.SearchString = searchString;
            #endregion

            //params to return to the view: collection as a paged list, page, pageSize
            return View(albums.ToPagedList(page, pageSize));
        }
        
    }
}

StoreFront.UI.MVC/Controllers/RecordLabelsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using Storefront.DATA.EF;

namespace StoreFront.UI.MVC.Controllers
{
    public class RecordLabelsController : Controller
    {
        private StoreFrontDB db = new StoreFrontDB();

        // GET: RecordLabels
        public ActionResult Index()
        {
            return View(db.RecordLabels.ToList());
        }

        // GET: RecordLabels/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            RecordLabel recordLabel = db.RecordLabels.Find(id);
            if (recordLabel == null)
            {
                return HttpNotFound();
            }
            return View(recordLabel);
        }

        // GET: RecordLabels/Create
        [Authorize(Roles = "Admin")]
        public ActionResult Create()
        {
            return View();
        }

        // POST: RecordLabels/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = "Admin")]
        public ActionResult Create([Bind(Include = "RecordLabelID,RecordLabelName,City,State,IsActive")] RecordLabel recordLabel)
        {
            if (ModelState.IsValid)
            {
                db.RecordLabels.Add(recordLabel);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(recordLabel);
        }

        // GET: RecordLabels/Edit/5
        [Authorize(Roles = "Admin")]
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            RecordLabel recordLabel = db.RecordLabels.Find(id);
            if (recordLabel == null)
            {
                return HttpNotFound();
            }
            return View(recordLabel);
        }

        // POST: RecordLabels/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = "Admin")]
        public ActionResult Edit([Bind(Include = "RecordLabelID,RecordLabelName,City,State,IsActive")] RecordLabel recordLabel)
        {
            if (ModelState.IsValid)
            {
                db.Entry(recordLabel).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(recordLabel);
        }

        // GET: RecordLabels/Delete/5
        [Authorize(Roles = "Admin")]
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            RecordLabel recordLabel = db.RecordLabels.Find(id);
            if (recordLabel == null)
            {
                return HttpNotFound();
            }
            return View(recordLabel);
        }

        // POST: RecordLabels/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = "Admin")]
        public ActionResult DeleteConfirmed(int id)
        {
            RecordLabel recordLabel = db.RecordLabels.Find(id);
            db.RecordLabels.Remove(recordLabel);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

StoreFront.UI.MVC/Views/Shared/_Layout.cshtml
@using Microsoft.AspNet.Identity

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />
    <meta name="description" content="" />
    <meta name="author" content="" />
    <title>@ViewBag.Title - Storefront Project</title>

    <!-- Favicon-->
    <link rel="icon" type="image/x-icon" href="~/_Archive/assets/favicon.ico" />

    <!-- Bootstrap icons-->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.5.0/font/bootstrap-icons.css" rel="stylesheet" />

    <!-- Bootstrap -->
    <link type="text/css" rel="stylesheet" href="~/Content/bootstrap.min.css" />

    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Gemunu+Libre:wght@300&display=swap" rel="stylesheet">

    <!--jQuery DataTables-->
    <link href="//cdn.datatables.net/1.10.20/css/jquery.dataTables.min.css" rel="stylesheet" />
    <link href="https://cdn.datatables.net/responsive/2.2.1/css/responsive.dataTables.min.css" rel="stylesheet" />

    @* ADDED jQueryUI CSS CDN - note: themenames are swappable.*@
    @*NOTE, Module 5 AJAX: find names at jqueryui.com/themeroller, gallyery tab (like excite-bike, south-street or sunny)*@
    @* AJAX - Step 1 - Add <link> for jQUery UI in the <head>, and add <scripts> for jQueryUI & jQuery AJAX at the bottom of layout *@
    <link rel="stylesheet" href="https://ajax.googleapis.com/ajax/libs/jqueryui/1.12.1/themes/south-street/jquery-ui.css">

    <!-- Core theme CSS (includes Bootstrap)-->
    <link href="~/Content/styles.css" rel="stylesheet" />

    <!--Paged List CSS-->
    <link href="~/Content/PagedList.css" rel="stylesheet" />

    <!--Custom Styling-->
    <link href="~/Content/customstyle.css" rel="stylesheet" />

    @RenderSection("htmlHead", required: false)

    <!-- HTML5 shim and Respond.js for IE8 support of HTML5 elements and media queries -->
    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
    <!--[if lt IE 9]>
        <script src="https://oss.maxcdn.com/html5shiv/3.7.3/html5shiv.min.js"></script>
        <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
    <![endif]-->
</head>
<body>
    <!--Logo-->
    <!-- Navigation-->
    <div class="container">
        <nav class="navbar navbar-expand-lg navbar-right">
            <ul class="main-menu nav navbar-nav">
                <li>@Html.ActionLink("Home", "Index", "Home")</li>
                <li>@Html.ActionLink("About", "About", "Home")</li>
                <li class="nav-item dropdown">
                    <a class="nav-link dropdown-toggle" data-toggle="dropdown" href="#" role="button" aria-haspopup="true" aria-expanded="false">Shop</a>
                    <div class="dropdown-menu shop-dropdown">
                        <button id="albumbtn" class="btn btn-light btn-lg">@Html.ActionLink("Albums", "Index", "Albums")</button>
                        <button id="artistbtn" class="btn btn-light btn-lg">@Html.ActionLink("Artists", "ArtistsQS", "Filters")</button>
                        <button id="recordlblbtn" class="btn btn-light btn-lg">@Html.ActionLink("Labels", "Index", "RecordLabels")</button>
                    </div>
                </li>
                <li class="nav-item dropdown">
                    <a class="nav-link dropdown-toggle" data-toggle="dropdown" href="#" role="button" aria-haspopup="true" aria-expanded="false">Account</a>
                    <div class="dropdown-menu account-dropdown">
                        @Html.Partial("_LoginPartial")
                    </div>
                </li>
            </ul>
        </nav>
    </div>

    <!-- Header-->
    <header class="bg-dark py-3">
        <div id="headerimgcontainer" class="container">
            <img src="~/Content/imgstore/deadbeatsheaderimg.jpg" />
            <div id="centeredtxt" class="centered">Welcome to Deadbeat Records</div>
        </div>
    </header>

    @RenderBody()

    <!-- Footer-->
    <footer class="py-5 bg-dark">
        <div class="container"><p class="m-0 text-center text-white">Copyright &copy; Tyler Rowe @DateTime.Now.Year </p></div>
        @if (Request.IsAuthenticated)
        {
            using (Html.BeginForm("LogOff", "Account", FormMethod.Post, new { id = "logoutForm"}))
            {
                @Html.AntiForgeryToken()
                <div id="welcomemsg" class="container">
                    <ul>
                        <li>
                            @Html.ActionLink("Hello " + User.Identity.GetUserName() + "!", "Index", "Manage", routeValues: null, htmlAttributes: new { title = "Manage" })
                        </li>
                    </ul>
                </div>
            }
        }
    </footer>

    <!-- preloader -->
    <div id='preloader'><div class='preloader'></div></div>

    <!-- jQuery Plugins -->
    <script type="text/javascript" src="~/Scripts/jquery.min.js"></script>
    <script type="text/javascript" src="~/Scripts/bootstrap.min.js"></script>
    <script type="text/javascript" src="~/Scripts/main.js"></script>

    <!--jQuery DataTables-->
    <script src="//cdn.datatables.net/1.10.20/js/jquery.dataTables.min.js"></script>
    <script src="https://cdn.datatables.net/responsive/2.2.1/js/dataTables.responsive.min.js"></script>

    <!--ADDEDjQuery UI CDN-->
    <script src="https://code.jquery.com/ui/1.12.1/jquery-ui.js"></script>

    <!-- ADDED jQuery Ajax CDN-->
    <script src="https://cdn.jsdelivr.net/jquery.ajax.unobtrusive/3.2.4/jquery.unobtrusive-ajax.min.js"></script>

    @RenderSection("scripts", required: false)


</body>
</html>

StoreFront.UI.MVC/Views/Shared/_OriginalLayout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")

</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Application name", "Index", "Home", null, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Home", "Index", "Home")</li>
                    <li>@Html.ActionLink("About", "About", "Home")</li>
                    <li>@Html.ActionLink("Contact", "Contact", "Home")</li>

                    @if (Request.IsAuthenticated && User.IsInRole("Admin")) {
                        <li>@Html.ActionLink("RolesAdmin", "Index", "RolesAdmin")</li>
                        <li>@Html.ActionLink("UsersAdmin", "Index", "UsersAdmin")</li>
                    }
                </ul>
                @Html.Partial("_LoginPartial")
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - My ASP.NET Application</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>